[build]
  command = "npm run build:netlify"
  publish = "dist/ssr/client"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions.ssr]
  external_node_modules = [
    "compression",
    "express",
    "firebase",
    "pinia",
    "quasar",
    "serialize-javascript",
    "serverless-http",
    "vue",
    "vue-router",
    "xlsx",
  ]
  included_files = [
    "dist/ssr/index.js",
    "dist/ssr/quasar.manifest.json",
    "dist/ssr/render-template.js",
    "dist/ssr/server/**",
  ]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr"
  status = 200
